name: 'Hello World'
description: 'Greet someone'
inputs:
  docker-name:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.docker-name }}.
      shell: bash
    - id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)"
      shell: bash
