on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: build and push docker to docker hub
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: deploy docker
        id: hello
        uses: ./.github/actions/deploy-docker
        with:
          docker-name: ${{ vars.DOCKER_NAME }}
