name: Docker Compose Actions Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the stack
        run: |
          echo "pass = ${{ vars.DOCKER_PASS }}"
          docker login -u ${{ vars.DOCKER_NAME }} -p ${{ secrets.DOCKER_PASS }}
          echo '-----------------------------------------------'
          echo '-----------------------------------------------'
          docker-compose -f docker-compose-build.yaml build --parallel
          echo '-----------------------------------------------'
          echo '-----------------------------------------------'
          docker push ${{ vars.DOCKER_NAME }}/udagram-frontend
          echo '-----------------------------------------------'
          echo '-----------------------------------------------'
          docker push ${{ vars.DOCKER_NAME }}/udagram-api-feed
          echo '-----------------------------------------------'
          echo '-----------------------------------------------'
          docker push ${{ vars.DOCKER_NAME }}/udagram-api-user
          echo '-----------------------------------------------'
          echo '-----------------------------------------------'
          docker push ${{ vars.DOCKER_NAME }}/reverseproxy