on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: actions/deploy-docker@v2

      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"